[ONL-5089] Updating README file
Ebury/huha pull request #34
Opened 2020-11-04 15:46 UTC by jafcalvente

2020-11-04 15:59 UTC, matallo requested changes

2020-11-04 15:59 UTC, matallo commented on README.md
> -![Chimo Bayo GIF](https://img.buzzfeed.com/buzzfeed-static/static/2015-07/9/15/enhanced/webdr06/anigif_enhanced-28562-1436468716-8.gif?downsize=715:*&output-format=auto&output-quality=auto)
This is probably my favourite change of the PR, finally, thanks!

2020-11-04 15:59 UTC, matallo commented on README.md
>  #### `Huha` class ####
🔥 trailing `####`

2020-11-04 15:59 UTC, matallo commented on README.md
>  #### `HuhaTask` class ####
same as above

2020-11-04 15:59 UTC, matallo commented on README.md
>  ### Automatic tasks ###
same as above

2020-11-04 15:59 UTC, matallo commented on README.md
> -### Reference ###
I'm not sure I'd keep this section in the readme, maybe a `docs.md` or `docs/reference.md` would be more suitable, thoughts?

2020-11-04 15:59 UTC, matallo commented on README.md
> +## References
We're not adding subtitles to the references section in other repositories, happy to preserve it, but we should be consistent (adding them everywhere or removing from here)

2020-11-04 15:59 UTC, matallo commented on CONTRIBUTING.md
> +* The [CHANGELOG](CHANGELOG.md) must be updated with relevant information about the changes that have been made.
Noticed this but didn't mention in previous PRs (as I'm not sure we'd want to preserve this). I know @earnubs was trialing automating something in Bosporus repository. Any insight or do you recommend us to keep editing the changelog and release notes manually?

2020-11-04 16:46 UTC, jafcalvente commented on README.md
> -### Reference ###
I like the idea of including it in its own file but I am not able to find a fully extended pattern about how call this kind of file and where put it into. I like `docs/reference.md`, but since other files like `CONTRIBUTING.md` and `VISION.md` are in the root, I would like to include also this file directly in the root and call it `REFERENCE.md`. Do you agree?

2020-11-04 17:11 UTC, matallo commented on README.md
> -### Reference ###
please do

2020-11-05 07:50 UTC, jafcalvente commented on README.md
> +## References
Resolved. I prefer to remove the subtitles here, so now is done.

2020-11-05 07:51 UTC, jafcalvente commented on README.md
>  #### `Huha` class ####
Done.

2020-11-05 07:51 UTC, jafcalvente commented on README.md
>  #### `HuhaTask` class ####
Done.

2020-11-05 07:52 UTC, jafcalvente commented on README.md
>  ### Automatic tasks ###
Done.

2020-11-05 07:52 UTC, jafcalvente commented on README.md
> -### Reference ###
Done.

2020-11-05 10:22 UTC, matallo commented on CONTRIBUTING.md
> +* The [CHANGELOG](CHANGELOG.md) must be updated with relevant information about the changes that have been made.
Let's keep it as it is while we find out a proper strategy 👍

2020-11-05 10:23 UTC, matallo approved these changes

2020-11-05 11:59 UTC, matallo approved these changes

2020-11-05 14:04 UTC, merged